use_frameworks!

platform :ios, '8.0'

target 'OBZuJianA_Example' do
  pod 'OBZuJianA', :path => '../'

  target 'OBZuJianA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
